const CONSTANTS = {
    GET_ORG_ID: 'GetOrgId',
    REFRESH: 'Refresh',
    GROUP_EXISTANCE_CHECK: 'GROUP_EXISTANCE_CHECK',
    MOVE_TO_GROUP: 'MOVE_TO_GROUP',
    GET_SETTINGS: 'GET_SETTINGS',
    UNGROUP_ALL_TABS: 'UNGROUP_ALL_TABS',
    CLOSE_ALL_GROUP: 'CLOSE_ALL_GROUP',
};

export {
    CONSTANTS
};